#!/usr/bin/env bash
################################################################################
# Header
# file: ./lib/head.sh
################################################################################
# odbpm
#
# Author: @mervinej
# License: MIT
#
# DO NOT EDIT THIS FILE DIRECTLY!
#
# This file is generated using 'make' in it's root directory
# from files within ./lib
################################################################################

